### ISSUE TITLE
Add Pre-installed Code Libraries for php and python

### ISSUE THREAD

**Issue by thousandsofthem** [iron-io/docs#10]
http://dev.iron.io/worker/reference/environment/

Section "Pre-installed Code Libraries (language-specific)"

We have "Ruby Gems Installed" but no corresponding section for php and python

At least php has some modules installed, like GD, mongo.

Full list can be retrieved from build script

**Comment by coopernurse** [comment]
From: `server_images/simple_worker.sh` on master branch

PHP:

```
php5-curl
php5-mysql
php5-gd
mongo (via pecl)
```

Python:

```
python-lxml
```
