### ISSUE TITLE
Disk Storage: Rewrite to reflect NG 

### ISSUE THREAD

**Issue by frommww** [iron-io/docs#101]
Recraft the Disk Storage article to take into account NG and inability to reference user_dir. 

Also rename title so it doesn't refernece Disk (Local Temp Storage).

http://dev.iron.io/worker/reference/disk-storage/

http://dev.iron.io/worker/reference/environment/

Local Disk Space (per Worker)

Each worker task has local disk space available to it for use on a temporary basis while the worker is running. You have full read/write privileges to create directories and files and can perform most ordinary file operations. You access this disk space via the user_dir directory.

**Comment by treeder** [comment]
This directory is given to the worker process with the "-d" program arg as specified here: http://dev.iron.io/worker/code/packaging/

Clients should provide helper methods to get this directory though if possible.

**Comment by paddycarver** [comment]
Should be taken care of.
