### ISSUE TITLE
Change all language pages to use .worker files and new config

### ISSUE THREAD

**Issue by treeder** [iron-io/docs#102]
Setup .iron.json file or ENV variables.

And then instead of the code upload we have now, show .worker files with upload command:

iron_worker upload myworker

**Comment by paddycarver** [comment]
@treeder for the languages that don't use NG (Python and PHP), using .worker files is impossible. Am I correct in assuming I should just ignore the .worker file for those pages?

**Comment by treeder** [comment]
@paddyforan what do you mean they don't use .worker files?  All languages should use cli with .worker files.

**Comment by paddycarver** [comment]
@treeder It's impossible to implement .worker files in any language other than Ruby. .worker files are just Ruby files. Last I heard, language pages were supposed to use that language's upload function if the library supported it (Python & PHP).

**Comment by treeder** [comment]
Should be cli for all languages. Add a note and link to the upload function in the library docs if they have one, but we should still stick to the standard way of doing it across all languages as default.

**Comment by treeder** [comment]
The .worker files and the cli don't care what language it is.

**Comment by paddycarver** [comment]
CLI does not support PHP or Python yet. This is as documented as it can be. When CLI supports PHP/Python, docs will be updated to reflect that.
