### ISSUE TITLE
Update writing your first worker page to use .worker files

### ISSUE THREAD

**Issue by treeder** [iron-io/docs#103]
This is step 3 on what to do to get started using IronWorker so should be drop dead simple. 

http://dev.iron.io/worker/start/first-worker/

Something along the lines of the new blog post would be good: http://blog.iron.io/2012/05/new-ironworker-command-line-interface.html?showComment=1337980098713#c1724122561880146714

**Comment by treeder** [comment]
Actually, that may just be obsolete now that we're multi-language. I found it because it was on the first worker page: http://dev.iron.io/worker/

So this page should be updated instead of that one: http://dev.iron.io/worker/languages/ruby/

**Comment by treeder** [comment]
And it's the first link on the left hand menu. Should that be there since it's only for ruby?

**Comment by paddycarver** [comment]
Obsolete, thanks to #119. #wontfix
