### ISSUE TITLE
Documentation needs BIG BOLD instructions on downloading the code package

### ISSUE THREAD

**Issue by carimura** [iron-io/docs#108]

**Comment by carimura** [comment]
test hipchat change

**Comment by paddycarver** [comment]
@carimura The API reference page? Sorry, not sure which doc we're talking about here.

**Comment by carimura** [comment]
Sorry I blasted these out too quickly....

I'm not even sure where I wanted to put this.. but somewhere in the getting started guides, or in the reference, there should be a very visible section for downloading the code package to ensure you are packaging and including dependencies correctly. It's a crucial debugging strategy that many people miss or don't know is available.

**Comment by paddycarver** [comment]
That gives me a good idea on where to put it. Thanks.

**Comment by paddycarver** [comment]
Merged into #119.
