### ISSUE TITLE
Scheduling should be a top level article under "Reference"

### ISSUE THREAD

**Issue by carimura** [iron-io/docs#112]
it's not even searchable right now...

**Comment by paddycarver** [comment]
@carimura Not sure what this means. Can you add more information?

**Comment by carimura** [comment]
Clarification: When searching for "schedule" or "scheduling" all the user gets is the API reference.... However since I submitted this issue, it appears that "scheduling" was added as a top level category under Reference. 

This is fine for now. We should also add a tutorial for how to schedule workers (and show code examples in all languages). That said we can probably close this ticket now.

**Comment by paddycarver** [comment]
Got it, thanks. Not a huge fan of the top-level link, but yes, a tutorial/article is definitely necessary. I'll make sure it's part of the new getting started flow, and make a note to do a more comprehensive page on it.
