### ISSUE TITLE
Bug in Library Configuration breadcrumb

### ISSUE THREAD

**Issue by frommww** [iron-io/docs#114]
Bad link in the Library Configuration breadcrumb

**Comment by paddycarver** [comment]
Got it, and know its root. Going to attempt a quick fix, but I really need to come up with a better way to handle breadcrumbs.

**Comment by paddycarver** [comment]
Should be fixed in commit d2bcf33a5ee50aba4434e64a2fd0366aad9b0bae. Waiting on Github to build the site now so I can verify.

**Comment by paddycarver** [comment]
Confirmed. @frommww, can you verify and close this when you get a chance?
