### ISSUE TITLE
div inside <a>

### ISSUE THREAD

**Issue by jamland** [iron-io/docs#132]
Do not use DIVs inside `<a>` ( `<p>`, `<small>`, etc.) if this is possible 
It is bad semantically and not valid html

![GitHub Logo](https://img.skitch.com/20120703-1wm5g6c8jejypcjnkgiff7uq5w.png)
# 

Actually i'm not sure why you need this DIVS at all, you can just set:
1. `<a> Write Your Worker </a>`

![GitHub Logo](https://img.skitch.com/20120703-nc4pxi7aw56u28wu1rwp4737je.png)

**Comment by paddycarver** [comment]
Sorry, this is a placeholder. @codybaker is working on a [much better version](https://s3.amazonaws.com/uploads.hipchat.com/6411/72372/o1vy14tyadt4824/Screen%20Shot%202012-07-03%20at%2011.43.36%20AM.png) that should be live in a couple hours.

We do use divs inside anchors elsewhere, though. I'll let you take it up with @codybaker, as it's not my specialty, but I thought the same thing. I checked with a friend whose knowledge on the spec I trust, and he assured me that it is semantically valid and considered the correct way to do things. As I said though, not my area of expertise. And frankly, as long as it looks good and is reasonably flexible, I don't care how it's done.

**Comment by jamland** [comment]
just diff elements (inline & block)
noticed this because of bad formatting...

but u need do care about it) less markup less css issues ;)
