### ISSUE TITLE
Broken Link: dot.worker

### ISSUE THREAD

**Issue by cdarwin** [iron-io/docs#133]
Under [Create & Upload A Code Package](http://staging-dev.iron.io/worker/#upload), the link to [.worker files documentation](http://staging-dev.iron.io/worker/reference/dotfiles) seems to be broken

**Comment by cdarwin** [comment]
I think it should point [here](http://staging-dev.iron.io/worker/reference/dotworker/) instead?

**Comment by paddycarver** [comment]
Should be fixed. Thanks.
