### ISSUE TITLE
IronWorker Environment misinformation

### ISSUE THREAD

**Issue by cdarwin** [iron-io/docs#134]
[IronWorker Environment](http://staging-dev.iron.io/worker/reference/environment/) page references Ubuntu 11.10, but we've updated to 12.04

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04 LTS
Release:        12.04
Codename:       precise

**Comment by paddycarver** [comment]
Good catch. Will fix.
