### ISSUE TITLE
Update "Getting started on Heroku" article

### ISSUE THREAD

**Issue by thousandsofthem** [iron-io/docs#141]
http://staging-dev.iron.io/worker/articles/platforms/heroku/
Article should be updated to use NG gem

**Comment by frommww** [comment]
This needs to be a priority per chat room thread.

Martin Bilski
14:12
Also, on heroku, your tutorial uses iron_worker gem. In your reference though you say it's deprecated. It's very confusing for a beginner to tell between the two ways (btw. I love the newer gem).
Alexander Shapiotko
14:12
for direct user - go to hud.iron.io and enter your login/password
Martin Bilski
14:12
The tutorial: https://devcenter.heroku.com/articles/iron_worker
Alexander Shapiotko
14:12
for addon - log in heroku, select the app, select addon
deprecated a lot
thanks for notice
Martin Bilski
14:13
Oh, I see. I guess I'm not a click click guy. 
Martin Bilski
14:14
Thank you, I'll continue playing. Nice thing. I plan to use it to offset sending emails for my website feedback app (criticue.com) -- work in progress but the production version is stable though a few more iterations are needed to make it truly usable.
Thanks!

**Comment by paddycarver** [comment]
Migrated to #189.
