### ISSUE TITLE
Weird scroll issue on pages with short content

### ISSUE THREAD

**Issue by carimura** [iron-io/docs#142]
On pages with short content (/worker/articles/databases is the only page I found like this) scrolling down does weird things... Firefox jumps, Chrome moves the menu up into the header.

**Comment by paddycarver** [comment]
We'll have to take a look at it. @codybaker

**Comment by paddycarver** [comment]
Should be fixed on staging, though we have a weird stutter bug in certain (rare) situations with the menu.
