### ISSUE TITLE
update how to merge/queue workers in _ng gem

### ISSUE THREAD

**Issue by rkononov** [iron-io/docs#143]
on this page http://staging-dev.iron.io/worker/languages/ruby/
in Merging -> workers section i didn't find methods how i could merge/queue workers in _ng gem -only how i can do this with old gem, i think we should say smth how to do this in _ng gem

**Comment by frommww** [comment]
The line below doesn't way where you put the code.merge_gem (in .worker, in your worker file etc.)

iron_worker_ng

Merging gems is simple in iron_worker_ng; you just use the code.merge_gem method:

**Comment by frommww** [comment]
The iron_worker section should have a note that this gem/approach is being deprecated in favor of _ng. Something like:

The iron_worker_ng gem is the recommended approach but if you're using iron_worker from previous work, you would merge gems in using the merge_gem command. (The iron_worker_ng approach has greatly improved merging and so if you run into any issues here, we highly recommend upgrading to iron_worker_ng.)
