### ISSUE TITLE
no such method - unmerge_gem in _ng gem

### ISSUE THREAD

**Issue by rkononov** [iron-io/docs#144]
http://staging-dev.iron.io/worker/languages/ruby/#environment

nokogiri - Note: You may need to merge nokogiri using merge_gem and then unmerge it using unmerge_gem

there is no such method unmerge_gem in _ng gem, this method exist in old gem

**Comment by paddycarver** [comment]
@rkononov should this note just be removed entirely? Does anyone know?

**Comment by rkononov** [comment]
just remove this line (i mean remove note about merge/unmerge nokogiri) - because in _ng gem merging doesn't make 'require' it in worker.
