### ISSUE TITLE
rvm users

### ISSUE THREAD

**Issue by rkononov** [iron-io/docs#147]
I think we should add some notes for rvm users about installing gem in all places we're writing 

sudo gem install iron_worker_ng

but rvm users should 

gem install iron_worker_ng

**Comment by manveru** [comment]
That's not just for rvm, but just about any ruby installation. `gem install` defaults to `gem install --user-install` after all.

**Comment by paddycarver** [comment]
So, @manveru @rkononov, if I'm hearing this right, I should just `s/sudo gem install/gem install/g`, right?

**Comment by manveru** [comment]
That's my recommendation, yeah.

**Comment by rkononov** [comment]
yes just remove sudo
