### ISSUE TITLE
Bad links to .js and .css

### ISSUE THREAD

**Issue by thousandsofthem** [iron-io/docs#15]
https://github.com/iron-io/docs/commit/f0fbf4456dd102f7e201bc75aaaaacbd028f7007

Header contain linsk to external resources from WEB project.

Problem: these links will change on every WEB commit that change resources content. 

Link example: http://www.iron.io/assets/application-3b1bd90e2a6ded693df68799dcd72a01.css

**Comment by paddycarver** [comment]
@carimura @thousandsofthem can we verify that this is still an issue? I thought we had fixed this, but I don't want to close the issue until I'm positive.

**Comment by thousandsofthem** [comment]
Tested. Issue not there anymore.
