### ISSUE TITLE
Add info on where to get project id and tokens on configuration page

### ISSUE THREAD

**Issue by treeder** [iron-io/docs#151]
http://dev.iron.io/articles/configuration/

Add at the top where to sign up and find their project id and tokens.

**Comment by paddycarver** [comment]
/articles/configuration will no longer be a page. It will now be available at /worker/reference/configuration, /mq/reference/configuration, and /cache/reference/configuration. An include is used, so all three pages just mirror the same content.

**Comment by treeder** [comment]
Any reason to have three pages if they will all be the same?

**Comment by paddycarver** [comment]
- Very little overhead--they're all kept up-to-date with each other automatically
- Puts the page where the user expects it (I want to know about IronWorker's config; I don't care if it's the same as IronMQ's)
- Consistent URL patterns

**Comment by treeder** [comment]
I think we want people to know it's the same for all services (and all languages). 

Also, give this a read through: http://support.google.com/webmasters/bin/answer.py?hl=en&answer=66359

**Comment by paddycarver** [comment]
"In the interest of letting users stop writing increasingly lengthy configuration files and start writing code, the maintainers of Iron.io's official client libraries have developed a global configuration scheme for all of Iron.io's services. This lets you set your project ID and token once to make them available to across all of Iron.io's services, and even across workspaces."

First two sentences, it mentions that the scheme is global, not product specific. Several times. It's also a recurring theme throughout the page.

Also, the webmasters article from Google notes that rankings will only be penalized if it appears you're trying to game the system. I hardly think 3 links that are duplicates will trigger a penalty.

Finally, think about it from a navigation/flow standpoint: I have this nice product-customised sidebar, but I click this link and suddenly I lose all those links? What the hell? It's throwing users from one part of the site into another unexpectedly.
