### ISSUE TITLE
Reference: CLI page -> Add example for queueing/scheduling

### ISSUE THREAD

**Issue by frommww** [iron-io/docs#152]
Suggest adding an example for queueing hello world and one for scheduling that would make use of the CLI options. Don't like having to look up and guessing what it looks like. 

-n -p --priority

-n -p --start-at  --run-times

For example params format not all that obvious.

iron_worker queue hello -p "{\"some_param\"=>\"some_value\", \"other_param\"=>[1, 2, 3]}"

**Comment by frommww** [comment]
For queueing and scheduling need to note that -n is the worker name, not the code name.

Big congnitive dissonance there. 

The worker file defines the worker name that is stored in IronWorker. Not the code name.

Upload uses the name of the .worker file ("hello.worker" in the case of Hello Worker)

Queue uses the worker name (name of .worker file)

**Comment by paddycarver** [comment]
Oh geeze. That is... something we really need to fix. Queue should be using the name of the code package.
