### ISSUE TITLE
Worker: Ruby page - enqueue.rb (instead of queue.rb) | schedule example

### ISSUE THREAD

**Issue by frommww** [iron-io/docs#156]
- file name should probably be "enqueue.rb" instead of "queue.rb" because that's what the examples use.
- can we include an example schedule the worker after queuing. That's not brought out. (should probably be for all the language pages...)

**Comment by paddycarver** [comment]
I'm going to hold off on adding the scheduling example to each page until after the launch. Two reasons:
1. We already have that information elsewhere.
2. It's pretty complex (requires raw API calls in Go and Node) so I'd like to write and test it outside of push-all-the-things-live mode, so it gets the attention it deserves.
