### ISSUE TITLE
Worker: CLI - edits

### ISSUE THREAD

**Issue by frommww** [iron-io/docs#157]
1) Would flip the first two sentences and put heroku, etc. after the introduction of the IW CLI. Seems weird to have the first sentence be about other platforms.

2) Needs to have a version number for CLI   > 1.9.3  (?)

3) "or the environment variables"  - environment variables aren't mentioned brefore so maybe just "or via environment variables"

4) Also, the list of config locations is noteworthy enough to put in a bullet list so it's easily scannable. 

5) The "For example, to override" should be a separate paragraph and should not have For example...  Just "To override these config methods, ... "

6) Wouldn't you put $PROJECT_ID instead of new_project_id_here as well as $WORKER  (to keep consistent)

7) " ... name of your .worker file ..."  (call out the .worker file as opposed to the .rb or other language file containing the worker. 

Where $WORKER is replaced by the name of your worker file, minus the .worker.

**Comment by paddycarver** [comment]
1) Fair enough

2) That's going to be too difficult to maintain. It's hard enough keeping track of changes, and nobody warns me when things are going on that need docs to update. I'm not going to be able to stay on top of that. :( No information is better than wrong information.

3) Fair enough.

4) I feel like that breaks up the flow too much. :-/ I'm not sure the configuration options should be given that much prominence here. They're not really the point of the page.

5) Why does this deserve its own paragraph? It's the same train of thought as the previous sentence.

6) Sure.

7) Good catch.

**Comment by frommww** [comment]
2) at least we need to let them know 1.8.7 won't work. I think 1.9.3 is the low bar and won't change all that much. 

4) in scanning the page, it wasn't all that apparen the options. seemed to make it more difficult / black magic than it is. I liked the simplicity of the CLI page that had that short paragraph (that I suggested being bullets). the global heirarchy and file heirarchy make it seem so complicated. 4-5 simple bullets would give you a good grouding to then dive in.

**Comment by frommww** [comment]
5) no problem. just thought it was a separate thought. the "for example" was a bit out of context is all.

**Comment by paddycarver** [comment]
2) Are you talking CLI version or Ruby version? Ruby version we should absolutely let them know. I thought you meant CLI version.

4) This is just making me want to choose one option, give a solid example for it (as we did in the languages pages), and link them to the configuration page if they want anything different. Most users won't care.

5) I'm not wedded to the "For example". I am fighting hard against adding more vertical space to what most users will see as something that should be a trivial step.

**Comment by frommww** [comment]
2) cli version. thought that it didn't run in 1.8.7 but if it does then no worries. keep it non versionized.

4) keep them here then. I like it compact and repeated. it's not the most obvious thing and sending them around the docs to one place makes it seem too much a treasure hunt.

5) keep paragraph together. just flow last sentence in. not ultra important. just somehting I hit while reading it.
