### ISSUE TITLE
Display context with code boxes

### ISSUE THREAD

**Issue by frommww** [iron-io/docs#158]
1) Know this is a pain since its throughout but i'd really like to see shell commands prefaced with a > to indicate that they're shell commands (not sure if that's the norm but some way to discern between what might go in a file and what would be a shell/terminal command)

> iron_worker queue $WORKER

2) The code boxes ideally should have some caption associated with them if at all possible. Something that would tell you where you should be typing (terminal, or queue.rb, 

In terminal
Sample queue.rb file
Sample .iron.json file

**Comment by paddycarver** [comment]
Can't use `>` in shell commands; would mess up the bash syntax highlighting. :-/

I'll look into doing fancier code boxes with @codybaker. See if we can't give some context visually.

**Comment by frommww** [comment]
no problem. figured there's be a reason. maybe captions will help. 

shell, .worker file  .iron.json/iron.json file, worker code, etc.

**Comment by dstaley** [comment]
Prefacing bash commands with `$` is a pretty common convention, and it also maintains the bash syntax highlighting (I checked to confirm).

Would look something like this:

```
$ gem install iron_worker_ng
$ iron_worker upload hello
$ ruby enqueue.rb
```

And we can add some aside text beneath the code block on the bottom right that says where it should be entered, such as `Terminal/Shell`, `.worker file`, or `iron.json`.

**Comment by paddycarver** [comment]
I'd still like to be able to display filenames and stuff with code boxes. :-/ We can chat about this--it's not super high priority--but I think something similar to what Chrome does on Android for tabs when you're in the tab overview would be cool.

**Comment by frommww** [comment]
Differentiating terminal from code files would be a big help. (Not sure if there's another distinction on local / environment files) but that would really help me grok this thing.) 
- terminal / command line stuff
- .iron.json file, .worker file
- worker file

Maybe in conjunction with diagrams, directory listings, as well as potentially labels, symbols or other way to convey what's what / what's where (Terminal, Local File, Code File) can help as well ...

**Comment by dstaley** [comment]
![Awesomeness](http://i.imgur.com/sWW4L.png)

What about something like this? for whichever code snippets we'd like, we can specify a title and a link. Links can be to more documentation about a file, or to download that code snippet.

**Comment by paddycarver** [comment]
I like the Download button, but that's going to be a lot of work, I think. Not sure how I feel about line numbering--it doesn't really serve a purpose (line numbering is only really useful when debugging) and it can interfere with copy/paste.

**Comment by dstaley** [comment]
This is actually already coded, and the download button (really just a manually set link) can be added where needed. Line numbers can be easily removed (and already are in the version I'm working with). The only bad news, however, is that it's all powered by Octopress, and I have no idea how to pull out just the code-highlighting ability. We do get some really awesome features out of it though, like code-highlighting caching, which reduces the build time greatly.

**Comment by paddycarver** [comment]
We can't use Octopress--we have too many custom, dynamic elements. Octopress would only store the generated HTML, not the markup that created it. Which is bad.

**Comment by frommww** [comment]
I like it. Line numbers to create copy paste issues and so hopefully won't be needed given we won't be having code segments that are too long.

**Comment by dstaley** [comment]
Alright, so take a look at this and tell me what your thoughts are. Ignore, for now, the visual design. I'm working on finding something I like that also fits in with the style of the dev center.

![Code Context](http://i.imgur.com/M2kOE.png)

The syntax is simple HTML:
Title with link:
`<figcaption><span>firstworker.worker </span><a href="http://j.mp/pPUUmW">Download </a></figcaption>`

Just a title:
`<figcaption><span>iron.json </span></figcaption>`

Since the HTML is really light, it's painless to add in CSS stylings, so we can definitely make them more prominent.

**Comment by frommww** [comment]
The centering of the file name and the same color header is a bit confusing. Wonder if left justified and a bit darker header might make it easier to scan. 

Also with iron.json we should also put (or .iron.json).?

I still think about letting people know where this file might exist (either local or uploaded to IronWorker). Not sure whether that's too confusing but just scanning the files and code samples it's not clear what goes where and how the pieces fit togehter (maybe a good old diagram can help with that but I'd still like to subtly drill in in via some type of caption).

Love the download btw.

**Comment by paddycarver** [comment]
> Also with iron.json we should also put (or .iron.json).?

I'd rather have them be opinionated and not vague for the sake of explaining every option.

> I still think about letting people know where this file might exist (either local or uploaded to IronWorker).

Maybe a different colour for each?

**Comment by frommww** [comment]
Hmm. I like a distinction between terminal/shell and code file but beyond that it could get noisy and less helpful.  

As for not explaining every option, then as long as there's a diagram that lists out the files and where they fit within the system.

Let's table the labeling of where the file goes. Maybe down the road we add a pinpoint that expands to show that diagram, highlighting where the file is in the diagram. (You/this file is here.)    :)

**Comment by dstaley** [comment]
Lookie here: new code contexts!
![Whoa, that looks good.](http://d.pr/i/C7P0+)

It's live in the code-context branch if you want to check it out.

**Comment by carimura** [comment]
@dstaley I'm generally anti-shading unless it's done very tight and crisp with clear sharp separators.

Try something like the way GitHub does it. A simple example of a clean box here: https://github.com/iron-marketplace/web-to-pdf

Then add a top bar exactly how GitHub ties in the top bar in each of these comment boxes.

Make sense?

**Comment by dstaley** [comment]
@carimura The problem with stronger gradients is that it creates a separation between the top bar and the code. Now, I'm not saying this is a bad thing, but I strongly prefer for the top bar to compliment the code. Here's an example that is heavily inspired by the GitHub comment top bar, with a bit of tweaking of colors.

![Ehh, not feeling this one.](http://d.pr/i/R9cL+)
