### ISSUE TITLE
Worker: System Environment page

### ISSUE THREAD

**Issue by frommww** [iron-io/docs#159]
Change from :

These are included because they are binary libraries. Language-specific libraries should be included as part of your worker code package, compiled to target Linux x64 architectures.

to: 

These are included because they are common binary libraries. Other binary libraries and files can be included as part of your worker code package, although you'll first need to compile them to target Linux x64 architectures.

**Comment by frommww** [comment]
Capital "T" to start last sentence.

Local Disk Space (per Worker)

Each worker task has local disk space available to it for use on a temporary basis while the worker is running. You have full read/write privileges to create directories and files and can perform most ordinary file operations. this directory is used as the current directory (”.”) when executing your workers.

**Comment by frommww** [comment]
Take out this sentence unless we have a good page for Scheduling.

> View the pages on Scheduling for more information on scheduling patterns and best practices.

**Comment by paddycarver** [comment]
First two: good catches.

Three: we have /worker/scheduling. Should be linked from there, though.
