### ISSUE TITLE
Create article on _ng use but with class definition with run() method

### ISSUE THREAD

**Issue by frommww** [iron-io/docs#169]
Create an article on using _ng approach but creating class and relying on implicit run() invocation. See/follow outcome of issue #65 in examples.

https://github.com/iron-io/iron_worker_examples/issues/65

Nicolas Blanco
7:37
Hi everybody!
Nicolas Blanco
7:39
I'm migrating from Ruby iron_worker to iron_worker_ng. I like the fact that worker definitions are now in .worker files, but really dislike to fact that workers are now just plain ruby. is it still possible to put the worker in a class, and execute a class method, etc ?
Ken Fromm
7:40
hmm, good question.
let me pin a note here for @andrew on this as well.
or @travis
that's something that we should write up in the dev center.
can you enter a ticket at the address above and we'll get back to you shortly with an answer?
Nicolas Blanco
7:42
Great, ok. I think it's really important for Ruby devs to write an example of worker that is encapsulated in at least a class or module. It's necessary for unit testing purposes.
Ken Fromm
7:44
understand. thanks.
Nicolas Blanco
7:48
maybe i could just encapsulate the worker logic in a class, merge the file, then in the worker a single line to execute the worker.
Ken Fromm
7:50
I'm sure it'll be something like that but travis and andrew can provide what we did originally. we went this route becuase it unified the treatment of languages but we do want to write this up to assist others trying to do the same thing.
Alexander Shapiotko
7:53
@NicolasBlanco you still can use old way - class witm run() menthod
Alexander Shapiotko
7:54
difference - unlike old gem, without iron_worker base class
Nicolas Blanco
7:55
ok then i create a class like class MyJob; def run; .... the code ...; end; end; and to enqueue ?
Alexander Shapiotko
7:56
yes. class name can be defined by second param in merge_exec.
like merge_exec('worker.rb', 'Worker')
for both .worker file definitions and ruby code
Alexander Shapiotko
8:00
use attr_reader to get information form payload as class methods
Nicolas Blanco
8:00
yes i know that, i'm trying right now, will tell you if i succeed

**Comment by paddycarver** [comment]
I feel like this belongs in examples or _ng's documentation. Should possibly be folded into the tutorial on debugging IronWorker. (#43)
