### ISSUE TITLE
Add polling loop to IronMQ examples code

### ISSUE THREAD

**Issue by treeder** [iron-io/docs#173]
Suggestion from customer to have this on this page: http://dev.iron.io/mq/

I agree, this is probably the most common usage of IronMQ. 

So instead of just get example, it would have the typical polling loop, something like:

``` ruby
while true
  msg = queue.get()
  if msg.nil?
    sleep 1
    next
  end
  # do something with the message here
  p msg.body
end
```

**Comment by manveru** [comment]
```
loop do
  unless msg = queue.get
    next sleep 1
  end
  # what's the message?
  p msg
  # other stuff
end
```

**Comment by paddycarver** [comment]
Removing my assignment.
