### ISSUE TITLE
IronMQ -> Create a FAQ

### ISSUE THREAD

**Issue by frommww** [iron-io/docs#176]
1. Iron-MQ has any limit in Queue creation ?
   There are no limits on the number of queues that can be created.
2. What's the Max size of the data that can be Pushed to queue ?
   Use can see details on the system environment here:

http://dev.iron.io/mq/reference/environment/

Max message size is 64KB although we do recommend using cache or block storage for large data and just passing data ids. Number of messages is unlimited.
1. Iron-MQ hosted in AWS, What are all the regions / Availability zones that Iron-MQ hosted /supported ?
   IronMQ is in AWS-US-East-1 and Rackspace-DFW although data persists in other zones and we have plans to move to other zones as failover very shortly.

http://dev.iron.io/mq/reference/api/
1. Different data / message types supported
   The API format is JSON and the message body can be in any format.
2. Different security levels that Iron-MQ supports
   IronMQ is HTTP-based and so we use HTTPS and OAuth for secure authentication.
3. Can we lock / tag the messages during push / processing Message from queue
   Not at this point. Can you provide use cases here so that we have a better understanding of what you're looking for?
4. Any Case study,
5. Number of requests that can handle by Iron-MQ service ?
6. High availability of Iron-MQ service
7. Scale to meet the increasing load

IronMQ is designed to handle massive amounts of requests and will scale out elastically to handle additional load. Please let us know your needs and we'll make sure we address them.
1. Any Limitation of Iron-MQ
   IronMQ is designed to be a flexible persistent message queue for cloud applications needing high availability and high throughput. And while we do not support some of the routing schemes or other features in the AMQP spec, we do provide robust messaging capabilities that meets most developers needs. We'd be happy to discuss any specific needs you might have.

Please let us know the visibility of the Iron-MQ service that fit in to applications
Can you explain a bit more as to what you're looking for. (Happy to address in a phone call.)

**Comment by paddycarver** [comment]
Removing my assignment.
