### ISSUE TITLE
Add Server AZ to Env Pages

### ISSUE THREAD

**Issue by paddycarver** [iron-io/docs#177]
Environment pages should specify which availability zone servers are in. (1b)

**Comment by treeder** [comment]
We shouldn't add this because AZ's are different for each aws customer so it doesn't really mean anything. We also want flexibility here for our high availability.

**Comment by paddycarver** [comment]
Thought about this as I made the issue, which is why I didn't just put it in right then. Wanted to double-check.

I feel both ways about this, but am totally okay with not including this at all. Seems like a lot of upkeep and ties our hands, and the information doesn't have a whole lot of applicable use cases, so it seems like the drawbacks outweigh the benefits.
