### ISSUE TITLE
Language pages: Add lines about passing in API args (priority for example)

### ISSUE THREAD

**Issue by frommww** [iron-io/docs#182]
Include in the queuing sections for the Language pages, instructions/examples on passing in API arguments, such as priority. Looked high and low and couldn't find it. 

Would be helpful to have the full list of available arguments so you don't have to search for them and then translate in the language-specific format (just an excerpt of the portion of line for each arg would suffice)

**Comment by paddycarver** [comment]
Removing my assignment.
