### ISSUE TITLE
Move over Michael's blog post to dev center

### ISSUE THREAD

**Issue by carimura** [iron-io/docs#184]
http://manveru.name/blog/show/2012-07-23/en/Keep-testing-your-iron-io-Ruby-Workers

@manveru can assist with providing HTML. Maybe?

Speaking of, hopefully we can standardize on some way to get blog posts into dev center. Maybe we even just link out to the blog post itself? BUt then we lose the search benefits.

**Comment by paddycarver** [comment]
Removing my assignment.
