### ISSUE TITLE
mq/projects/get_started python demo code seems wrong

### ISSUE THREAD

**Issue by FedericoElles** [iron-io/docs#186]
https://hud.iron.io/mq/projects/*project_id*/get_started

I believe the python demo code is wrong:

``` python
# Get a message
msg = ironmq.getMessage(queue_name="my_queue")
```

this returns a directory of messages, not a single message...

``` python
singleMsgId = msg['messages'][0]['id']
```

**Comment by paddycarver** [comment]
Thanks for pointing this out! I'll make an issue in the HUD, which is where the bug is, but which doesn't have a public issue tracker.
