### ISSUE TITLE
MQ: API reference - need inclusion of multiple post option

### ISSUE THREAD

**Issue by frommww** [iron-io/docs#187]
Post operations in IronMQ support a multiple message option.

This needs to be documented in the reference as well as in the github code libs.

```
# options:
#  :queue_name => can specify an alternative queue name
#  :delay => time to wait before message will be available on the queue
#  :timeout => The time in seconds to wait after message is taken off the queue, before it is put back on. Delete before :timeout to ensure it does not go back on the queue.
#  :expires_in => After this time, message will be automatically removed from the queue.
def post(payload, options={})
  batch = false
  if payload.is_a?(Array)
    batch = true
    msgs = payload
  else
    options[:body] = payload
    msgs = []
    msgs << options
  end
  to_send = {}
  to_send[:messages] = msgs
  res = @client.parse_response(@client.post(path(options), to_send))
  if batch
    return res
  else
    return ResponseBase.new({"id"=>res["ids"][0], "msg"=>res["msg"]})
  end
end
```

**Comment by edsrzf** [comment]
This is documented with an example, but maybe it could be clearer.

**Comment by johnnyc** [comment]
Somehow I was messaged regarding this... i believe you tagged the wrong John

**Comment by frommww** [comment]
@johnnyc  sorry about that. Transferred over parts of a chat and it had the @ reference in it. Took it out.

**Comment by frommww** [comment]
http://dev.iron.io/mq/reference/environment/

Also adjust the message size note - does not include the header information apparently. 

MichaelF
token not in the message,
and the size limit is only applied on the http body, not the headers

EvanS
Yep, you're right

Message Var Default Maximum Notes
Message Size    --  64KB    Includes header (token, delay, timeout, expiration).
