### ISSUE TITLE
Code switcher is partially broken

### ISSUE THREAD

**Issue by carimura** [iron-io/docs#19]
http://dev.iron.io/worker/start/first-worker/

Ruby doesn't show up on some of the switchers... then switching at top works. Just need to look into this.

**Comment by thousandsofthem** [comment]
I know about it. 
Reason: All central content of http://dev.iron.io/worker/start/first-worker/ are replacing when anybody clicks on "php/python" or "ruby" language switcher.
It means all code blocks on page are different between ruby and non-ruby tutorials, so, as example, link to "ruby" from "php" tutorial has no sense. 
If you have any idea how to handle this issue more gracefully, let me know.

**Comment by carimura** [comment]
hmmm.... we may need to revisit how this is all handled - but I think Paddy has it under control also. Regardless, needs to be thought about and fixed soon.

**Comment by paddycarver** [comment]
Alexander and I discussed this a fair bit before launch, and as far as I can tell, his solution is the best we have available to us. This sort of tomfoolery won't be necessary when/if NG becomes top dog and we can use that instead of iron_worker_ruby, but until then, I can't see any neater way to resolve this.

**Comment by frommww** [comment]
btw, order should be Ruby Python PHP ...  

Want it to be consistent in the language switcher, docs text, hud, etc.

**Comment by carimura** [comment]
Paddy, I think we need to get on the phone and discuss this. The way it exists right now is broken. The Ruby option is only shown in the top switcher, and then when it's selected, the other languages disappear from all the other switchers.

Why don't we just get rid of the language switcher from all code blocks except for the very top? This is how it was originally...

**Comment by paddycarver** [comment]
That is also a possible solution. I don't have a strong preference between how we're doing it now and just removing everything but the top one. Should I remove all but the topmost switcher, fix the ordering as per @frommww's note, and call it a day?

**Comment by carimura** [comment]
\o/

**Comment by paddycarver** [comment]
I'll take that as a "yes". Fix incoming, probably later tonight. Want to test on my own system first, and I'm not in Buffalo this weekend (so away from the installation I have on my main machine).
