### ISSUE TITLE
Article on how to store results from IronWorker tasks in MQ or Cache

### ISSUE THREAD

**Issue by treeder** [iron-io/docs#192]
See this thread for background: https://twitter.com/treeder/status/232905907040833536

It started with him wanting to get all the logs from IronWorker and parse through his logs for results.

**Comment by frommww** [comment]
The web-crawling example in nokogiri does this. Can use this as an example. 

The blog post I'm writing up on nokogiri highlights this but we should probably include basics as well as general guidelines and patterns.

**Comment by paddycarver** [comment]
Removing my assignment.
