### ISSUE TITLE
Highlight that .worker file are ruby script.

### ISSUE THREAD

**Issue by plehoux** [iron-io/docs#193]
http://dev.iron.io/worker/reference/dotworker/ 
## Tips

.worker file internally are just  ruby script, you could use constructions like this:

``` ruby
unless ENV['dev']
  file 'build.sh'
  build 'sh build.sh'
end
```

**Comment by paddycarver** [comment]
I'd consider documenting a process for environment stuff, but I'd really like to refrain from documenting that the .worker files are just Ruby scripts. That means we have to support Ruby execution in .worker files no matter what, even if we switch the language our CLI is built on.

It's the difference between a promise and an implementation detail--I'd really like to keep the Ruby nature of the .worker files an implementation detail, if possible.
