### ISSUE TITLE
Make it clear that .worker file is worker_name.worker

### ISSUE THREAD

**Issue by carimura** [iron-io/docs#194]
in all places .worker is referenced

**Comment by paddycarver** [comment]
Files to update:

./_includes/sidemenu_worker.html
./_posts/2012-05-31-solutions-image-processing.md
./partner_docs/heroku_worker.md
./worker/index.html
./worker/languages/go/index.md
./worker/languages/java/index.md
./worker/languages/nodejs/index.md
./worker/languages/php/index.md
./worker/languages/ruby/index.md
./worker/languages/ruby/merging-files-and-dirs/index.md
./worker/languages/ruby/merging-gems/index.md
./worker/reference/cli/index.md
./worker/reference/dotworker/index.md
./worker/reference/index.html
