### ISSUE TITLE
Anchors and sidemenu highlight don't work for "local disk" and "logging"

### ISSUE THREAD

**Issue by carimura** [iron-io/docs#196]
In SAFARI MAC. Reported by user.

http://dev.iron.io/worker/reference/environment/#local_disk_space_per_worker

http://dev.iron.io/worker/#inspect

**Comment by paddycarver** [comment]
There's no way to fix this that I can think of. The links are to part of a page, so the link that's highlighted on the page is the one for the page.

It's part of the reason those links weren't originally included in the sidemenu.
