### ISSUE TITLE
Delay in posting time?

### ISSUE THREAD

**Issue by andrebruton** [iron-io/docs#205]
> delay: The item will not be available on the queue until this many seconds have passed. Default is 0 seconds.

When posting a message, what are the valid limits one can use for the Delay option. I hope it is longer than 15 minutes! I'm looking for at least 7 days or even better 31 days.

**Comment by carimura** [comment]
Hey Andre,

Your messages have a maximum delay of 7 days. What are you trying to do? There are probably other ways we can solve your problem.

Feel free to jump into our live chat at http://get.iron.io/chat

Chad
