### ISSUE TITLE
Uploading worker - include some failed routes to explain how to do it corrected.

### ISSUE THREAD

**Issue by frommww** [iron-io/docs#206]
We seem to have seen this a few times. Questions on "No exec specified".  Seems like we should not just sohw the right way to upload but also incorrect ways so taht people can say, "Ah, I know what I did wrong."

User
10:01
Pretty much a newbie with ironworker. I keep getting this error when I am uploading my workers.
User
10:02
------> Uploading code package
        No exec specified
/Users/Sean/.rvm/gems/ruby-1.9.2-p290@rstatus/gems/iron_core-0.4.2/lib/iron_core/logger.rb:50:in `raise_exception': No exec specified (IronCore::Error)

**Comment by blakecash** [comment]
Yeah I am an idiot.. haha. Just realized my file path was wrong. I got it
thanks.

**Comment by frommww** [comment]
@blakecash  Glad you got it resolved. All the same, we should a) have a better error message in the CLI as well as have some troubleshooting steps in docs. (Sorry for outing above. I edited it after realizing it's public. Doh!). Let us know if you need any further assistance.

**Comment by carimura** [comment]
Also @iced @romand-ironio FYI on CLI log output.

**Comment by paddycarver** [comment]
Removing my assignment.
