### ISSUE TITLE
IronWorker: Examples on CLI page 

### ISSUE THREAD

**Issue by frommww** [iron-io/docs#208]
Can we add some examples on the CLI page for queueing, scheduling, and getting logs. Per the article on Designing Great Ideas, many people pick up immediately from examples as opposed to the command description. 

http://dev.iron.io/worker/reference/cli/

Also max_concurrency (and I think delay and timeout) are missing.

**Comment by paddycarver** [comment]
A lot of these (logs, schedules, queuing) were already covered. I expanded the examples pretty significantly.
