### ISSUE TITLE
Document syntax of `gemfile` command in .worker files

### ISSUE THREAD

**Issue by langalex** [iron-io/docs#209]
On [this page](http://dev.iron.io/worker/reference/dotworker/) under `gemfile` it states `The groups to include in the merge. Defaults to all the groups. (optional)`, but it is not explained how to include/exclude groups. Do you pass in a string, an array?

**Comment by paddycarver** [comment]
@langalex can you check out the page you linked to now, and let me know if that makes things any clearer?

**Comment by langalex** [comment]
much better. thanks!
