### ISSUE TITLE
Error in IronCache api reference

### ISSUE THREAD

**Issue by thousandsofthem** [iron-io/docs#212]
http://dev.iron.io/cache/reference/api/#add_an_item_to_a_cache

Actual (invalid) text:

```
Required:
* value: The item’s data
```

Should be:

```
body: The item’s data
```

Looks inconsistent with all other places though.

valid PUT curl request:

```
% curl -i -H "Content-Type: application/json" \
> -H "Accept: application/json" \
> -H "Authorization: OAuth xxxxxxxxxx" \
> -X PUT -d '{"cache_name":"some_cache_name","body":"foo"}' \
> "https://cache-aws-us-east-1.iron.io:443/1/projects/yyyyyyyyyy/caches/urls/items/1"
```

**Comment by paddycarver** [comment]
Looking at the source, that doesn't appear to be the case? I'll test with curl to confirm.

**Comment by paddycarver** [comment]
According to curl, either operation works as intended.

**Comment by edsrzf** [comment]
So you're saying "body" works? I'm pretty sure it shouldn't.

**Comment by paddycarver** [comment]
@edsrzf My assumption is that it is because of the name of the struct key in the API. I've created an issue in the cache repo that we can discuss in. But yes, I'm saying both values are accepted.
