### ISSUE TITLE
REST documentation lack information about retries

### ISSUE THREAD

**Issue by thousandsofthem** [iron-io/docs#215]
Page
http://dev.iron.io/worker/reference/api/#upload_a_code_package

Should contain information about optional parameters `retries` and `retries_delay` :
http://blog.iron.io/2012/09/new-feature-auto-retry-for-ironworker.html

**Comment by paddycarver** [comment]
Good catch, thanks. It's included in the CLI page, but I must've forgotten to add it to the API. I'll add that today.
