### ISSUE TITLE
Scrolling Sidebar breaks on mobile

### ISSUE THREAD

**Issue by paddycarver** [iron-io/docs#219]
If you zoom in on mobile, the scrolling sidebar gets layered over the content. Is there any way we can (_reliably_) detect when the user is using a mobile browser, and disable the scrolling sidebar when they are?

**Comment by dstaley** [comment]
@paddyforan When you get the chance, check this out and make sure it works as you expect. I'm having serious cases of "run jekyll and while it's generating forget what I wanted to look at". It should disable the sidebar on any browser that allows the user to zoom in. This means that when you zoom on a mobile device, the sidebar should not scroll, but also that when you `Ctrl/Cmd + +` on a desktop browser, that it's disabled as well.

**Comment by paddycarver** [comment]
This looks right. It disables the scrolling sidebar entirely on mobile, but I'm okay with that. I'll merge it in and push it tonight.
