### ISSUE TITLE
Add iron_go lib to all services client lists

### ISSUE THREAD

**Issue by treeder** [iron-io/docs#221]
https://github.com/iron-io/iron_go

It supports all our services.

**Comment by paddycarver** [comment]
@treeder does this replace iron-io/iron_mq_go and the ilk, or are we maintaining two official Go libraries for our services?

**Comment by treeder** [comment]
I believe this replaces the old go one(s). @edsrzf @manveru can you confirm that?

**Comment by manveru** [comment]
The new one is maintained by me, and covers more functionality than the old one, but it's not API compatible.
So I think we should promote it as the standard go lib, but inform people using the old one, maybe adding some message in `init()` that points to the new version?

**Comment by paddycarver** [comment]
@manveru I'll let you and @edsrzf decide that between yourselves. Really, what I need(ed) to know was whether to list both, or just the one.

Sounds like we should just list the one. I'll update the pull request, then @dstaley can check it and merge it in at his leisure.
