### ISSUE TITLE
Sidemenu weird behavior on devices with small displays

### ISSUE THREAD

**Issue by thousandsofthem** [iron-io/docs#226]
How to reproduce:
- open dev.iron.io/worker in phone's browser and scroll down

Note: depends on zoom level, works good in overview mode (whole page fits into screen)

Default android browser:
![](http://i.imgur.com/7BR2x.png)
![](http://i.imgur.com/4xVJJ.png)

Chrome for Andoroid:
![](http://i.imgur.com/H6G67.png)

P.S. Exact environment:
- OS: Android 4.1.1
- Phone: Galaxy S3

**Comment by paddycarver** [comment]
Diagnosis: @dstaley wrote code that fixed this, I told him I would merge it in, I forgot to.

He just opened a pull request, so we'll get that fixed.

**Comment by thousandsofthem** [comment]
ehm, duplicate of #219
