### ISSUE TITLE
Combine all /worker/languages pages

### ISSUE THREAD

**Issue by paddycarver** [iron-io/docs#237]
All /worker/languages pages should use the same template, and we should just be plugging in words, phrases, and code samples. There's no reason to be maintaining half a dozen versions of the same exact page.

Ideally, I'd like to remove all those pages, and just include the information they had in /worker, with a language switcher--it seems like we have two "Getting Started" guides in Dev. I'd like to only have one. Thoughts on that? @frommww? @carimura? @dstaley?

**Comment by frommww** [comment]
As long as there is enough information to go from step 1 to step zeta. Hate it when docs have only partial data and you have to move to a couple of them to piece them together.

**Comment by dstaley** [comment]
@frommww The main idea (at least behind this issue) is to combine /worker (the main getting started) with /worker/languages/ruby, /worker/languages/php, /worker/languages/python, etc into one article that the viewer can easily switch to their language.

**Comment by frommww** [comment]
no objections here.
