### ISSUE TITLE
Some links should open in a new tab

### ISSUE THREAD

**Issue by paddycarver** [iron-io/docs#239]
Some links (client libraries, links to some external sites, etc) should open in a new window by default.

**Comment by dstaley** [comment]
@paddyforan good to close this?

**Comment by paddycarver** [comment]
Did it get fixed? Sorry, I didn't notice. If you're confident it's fixed, close it.

**Comment by paddycarver** [comment]
I'm not seeing the changes on the site...?

**Comment by dstaley** [comment]
@paddyforan Huh, thought I sent a pull request. Let me do that and have you check it out.
