### ISSUE TITLE
IronWorker Sys Environment -> Max Scheduled Tasks -> Max Schedules

### ISSUE THREAD

**Issue by frommww** [iron-io/docs#263]
Change Max Scheduled Tasks (per Project) to Max Schedules

http://dev.iron.io/worker/reference/environment/

Want to differentiate a Schedule from a Task given a schedule can spawn any number of tasks. 

(Also, take out Per Project given it should be by user account).

**Comment by paddycarver** [comment]
Would it be possible unassign me from this issue, or close the issue?
