### ISSUE TITLE
Queue vs scheduleing

### ISSUE THREAD

**Issue by jtallieu** [iron-io/docs#278]
The 2nd example in this link led me to believe that when I queue a task with a delay, that behind the scenes a schedule was created as the example shows the return dict being set to "schedule".
http://dev.iron.io/worker/scheduling/

**Comment by treeder** [comment]
Hi @jtallieu ,

You should use delay if you want a task to run once in the future. If you want it to run on a recurring schedule, then you should create a schedule with "run_every" so it repeats.

**Comment by jtallieu** [comment]
I was saying that using the name "schedule" as the assignment variable of
the return from the queue method was misleading.  It actually returns a
task.

**Comment by jtallieu** [comment]
Also, reading this http://dev.iron.io/worker/reference/api/#queue_a_task

"_delay_: The number of seconds to delay before actually queuing the task.
Default is 0."

lead me to think that after calling the queue method, if there was a delay,
that the task would not show as "queued" until after the delay has expired,
when in actuality, it is queued immediately.

**Comment by treeder** [comment]
Got it, should be named "task", you're right. 

Regarding "delay" it is queued with a delay. So although the status is "queued", it won't run until the delay passes.
