### ISSUE TITLE
Page on connecting to Heroku Postgres

### ISSUE THREAD

**Issue by carimura** [iron-io/docs#286]
From customer below:

1 - can't use the heroku database url as it appears in the heroku
config env, must use credentials as you get them from "hu
pg:credentials HEROKU_POSTGRESQL_SILVER_URL" (for example)

2 - must specify adapter in the establish_connection call as in
ActiveRecord::Base.establish_connection(
    {
        adapter:  "postgresql",
        sslmode: "require",
        <etc>

3 - must specify sslmode in connection call

**Comment by hanchang** [comment]
Bump?
