### ISSUE TITLE
Incorrect GET/POST documented/implemented for Touch/Release?

### ISSUE THREAD

**Issue by iluffsyeww** [iron-io/docs#287]
In the IronMQ REST/HTTP API documentation (http://dev.iron.io/mq/reference/api/), the Touch and Release messages are documented as POSTs with no body. Is this correct? I've been trying to use these but I'm getting 400 responses. Am I missing something? Is there a body required, or am I just doing something wrong?

This is using the .NET library, by the way.

**Comment by frommww** [comment]
See if you can connect with any of the devs in our public chat room (get.iron.io/chat).

**Comment by treeder** [comment]
Hi @iluffsyeww, try an empty json body, ie: {}

**Comment by iluffsyeww** [comment]
Thanks, that worked. I should've thought of that.

**Comment by treeder** [comment]
We'll add it to the docs though regardless, sorry it wasn't clear.
