### ISSUE TITLE
Push Queue: No documentation on what my endpoint should expect to receive

### ISSUE THREAD

**Issue by threeseed** [iron-io/docs#305]
There should be documentation of the format of the JSON message that IronMQ will be posting to my endpoint.

**Comment by featalion** [comment]
Hi! Message's body will be POST to your endpoint as is in request body. There is no special format, but it's string.

Assume, you post "hello push queue" to your push queue. Then, on the endpoint(s) you can read request body.
I tested it in Rails app:

``` ruby
class DataController < ApplicationController
  # this is endpoint in push queue
  def push_data
    pushed_msg_body = request.body.read
    Rails.logger.info push_msg_body
  end
end
```

In log I see: `2013-04-28T13:53:21.323751+00:00 app[web.1]: hello push queue`.

Anyway, I will add this example to documentation on Dev Center.

**Comment by featalion** [comment]
Added to documentation. Will be pushed to Dev Center with the next docs release.
