### ISSUE TITLE
Push Queue: Insufficient documentation on retry behaviour

### ISSUE THREAD

**Issue by threeseed** [iron-io/docs#306]
It's not clear what will happen:

1) When the retries are exhausted

2) Behaviour when you have multiple end points in unicast mode

**Comment by treeder** [comment]
We'll review the docs with your suggestions soon, but to answer your question:

1) When retries are exhausted, the message is archived and only available via the message ID. We will very soon have a better way to get at messages that weren't sent successfully. 

2) Unicast means it will try all the endpoints until it gets a successful response, ie: a 20X status code. Once it receives a 20X from an endpoint, it won't try any others. This ensures that only one endpoint gets the message. 

Thanks for submitting these issues!
