### ISSUE TITLE
Push Queue: Insufficient documentation on queuing behaviour

### ISSUE THREAD

**Issue by threeseed** [iron-io/docs#307]
It's not clear about how push queues works with multiple messages.

If I have 100 messages in the queue will it:

a) Immediately send 100 requests to my endpoint.
b) Send 1 request and then block.

**Comment by treeder** [comment]
It's currently not rate limited so it will immediately send each message as they are put on the queue. It will not send existing messages on the queue though, only messages added after you change it to a push queue.
