### ISSUE TITLE
Add security group id to docs

### ISSUE THREAD

**Issue by treeder** [iron-io/docs#330]
To here: http://dev.iron.io/worker/reference/security/#security_groups_and_ip_ranges

id: sg-0d500c64

**Comment by borgified** [comment]
ugh wrong window.. pls disregard everything coming from borgified/docs

**Comment by treeder** [comment]
@borgified I can't remember why we need the id vs the name? Can you remind me.

**Comment by borgified** [comment]
Sorry, I don't have additional info to add to help remind you. I just followed what the issue #330 said and did it (w/o context).
