### ISSUE TITLE
Add information about perl support

### ISSUE THREAD

**Issue by thousandsofthem** [iron-io/docs#349]
Add information about perl support
- Sidebar
- Syntax reference http://dev.iron.io/worker/reference/dotworker/#syntax_reference
- http://dev.iron.io/worker/reference/environment/#default_languages_versions

**Comment by treeder** [comment]
Good blog article about it too: http://blog.carloslima.name/blog/2013/11/05/running-perl-workers-on-iron-dot-io/

Could just have some basic info and then link to this post.
