### ISSUE TITLE
Add Twilio Integrations

### ISSUE THREAD

**Issue by paddycarver** [iron-io/docs#36]
Add an article on integrating with Twilio for worker integrations.

**Comment by jeffreymb** [comment]
I would be interested in hearing the recommended procedure for this. I am seriously considering using IronWorker for sending out SMSes with Twilio and some input would be very useful.

**Comment by paddycarver** [comment]
@Icode4food Awesome! I'll bump this in priority and try to get something written in the next few days.

In the meantime:

[This](https://github.com/iron-io/iron_worker_examples/tree/master/ruby/twilio) is an example for using twilio using the `iron_worker_ruby` gem.

[This](http://kick-more-apm.appspot.com/#textsender) is an example in Python I did for a presentation about our API.

Essentially, sending out SMS messages is exactly the same on IronWorker as it is everywhere else: import Twilio's client library, and make the API call.

Hopefully I'll have some more detailed docs created soon. Sorry for the delay!

**Comment by paddycarver** [comment]
We're going to try to remove integrations from the articles section, to keep things from getting cluttered and obscuring the _real_ articles. I'm not convinced documenting every possible integration is tenable.
