### ISSUE TITLE
Bug in IronWorker Documentation

### ISSUE THREAD

**Issue by mikkoi** [iron-io/docs#369]
Documentation to API "Upload or Update a Code Package" (/projects/{Project ID}/codes) states:
"Response

The response will be a JSON object containing a “msg” property that contains a description of the response.

Sample:
{
    "msg": "Upload successful."
}
"

When using, I also got back from IronWorker service the id for the code package:
"Returned HTTP response code:200
Returned HTTP response:{"id":"529b1117d16f936cfa00a0ca","msg":"Upload successful."}
"

So I'm wondering if the returned id is a permanent feature?
## 

Mikko Koivunalho
mikko.koivunalho@iki.fi

**Comment by treeder** [comment]
I believe that's a permanent feature and should be documented as such. cc @Stephenitis
