### ISSUE TITLE
FYI:   Docs dont match implementation

### ISSUE THREAD

**Issue by cavanaug** [iron-io/docs#404]
/projects/{Project ID}/queues/{Queue Name}  POST    Update a Message Queue

Should return
201 Created: Successful POST

But instead returns a
200

**Comment by treeder** [comment]
That's for updating a queue, not creating it. Queues are typically made automatically when you post a message.

**Comment by cavanaug** [comment]
It's still a POST which I think should return a 201.   But I'm a bit
obsessive on details.  No worries.

FYI.   That call will create a new queue if it doesn't already exist.

## 

John Cavanaugh
Sent from my iPhone

On May 22, 2014, at 5:25 PM, Travis Reeder notifications@github.com wrote:

That's for updating a queue, not creating it. Queues are typically made
automatically when you post a message.

—
Reply to this email directly or view it on
GitHubhttps://github.com/iron-io/docs/issues/404#issuecomment-43959642
.

**Comment by treeder** [comment]
Ahh, you're referring to the docs at the top that say: 

```
200 OK: Successful GET
201 Created: Successful POST
```

Is that what you're referring to?  That's wrong, we'll get that changed.

**Comment by cavanaug** [comment]
Yep, that's what I was referring to.

## 

John Cavanaugh
Sent from my iPhone

On May 23, 2014, at 10:06 AM, Travis Reeder notifications@github.com
wrote:

Ahh, you're referring to the docs at the top that say:

00  OK: Successful GET
201 Created: Successful POST

Is that what you're referring to? That's wrong, we'll get that changed.

—
Reply to this email directly or view it on
GitHubhttps://github.com/iron-io/docs/issues/404#issuecomment-44036352
.
