### ISSUE TITLE
CLI v2 iron.json environments

### ISSUE THREAD

**Issue by alnutile** [iron-io/docs#467]
Does this still work as in the docs http://dev.iron.io/worker/beta/cli/

```
iron worker upload helloworker --env development
iron worker upload helloworker --env staging
iron worker upload helloworker -e test
iron worker upload helloworker -e production
```

The docs note that `iron worker upload --help` will show options but this is the output of that

![options](https://dl.dropboxusercontent.com/s/61hjufwh68fek9o/Screenshot%202015-04-28%2005.35.20.png?dl=0)

And when I try and upload using any of these commands

```
iron worker upload --stack php-5.6 ExampleTwoWorker.zip --env development php workers/ExampleTwoWorker.php

iron worker upload --stack php-5.6 --env development ExampleTwoWorker.zip php workers/ExampleTwoWorker.php

iron worker upload --stack php-5.6 ExampleTwoWorker.zip php workers/ExampleTwoWorker.php  --env development 
```

I get this error `did not find project id in any config files or env variables`

The iron.json looks like

```
{
  "production": {
    "token": "foo",
    "project_id": "bar"
  },
  "development": {
    "token": "foo2",
    "project_id": "bar2"
  }
}
```

If I set the file back to one environment 

```
{
    "token": "foo",
    "project_id": "bar"
}
```

and remove the --env switch all works again

thanks

**Comment by rdallman** [comment]
hi @alnutile please see changes from #468 . in summary, sorry, the docs were just misleading, but this functionality is supported. The first command you gave should be like this:

```
$ iron --env development worker upload --stack php-5.6 ExampleTwoWorker.zip php workers/ExampleTwoWorker.php
```

let us know if you get it working ok or not :)
appreciate the feedback

**Comment by alnutile** [comment]
great will try shortly thanks!
