### ISSUE TITLE
Docs don't mention updated requirement to always have a JSON body for all requests

### ISSUE THREAD

**Issue by EmilyMcCarthy** [iron-io/docs#546]
You used to be able to not send any body for requests that do not require one (ie, http://dev.iron.io/worker/reference/api/#cancel_a_scheduled_task) but now all requests require at least a {} body, and none of the docs reflect this.

**Comment by vasilev** [comment]
@JohnMcCarthy , thanks for report. 
API fix will be shipped soon. No need to change docs.
