### ISSUE TITLE
Duplicated link to heroku integration

### ISSUE THREAD

**Issue by thousandsofthem** [iron-io/docs#6]
http://dev.iron.io/worker/articles/platforms/

Duplicated link:

![](http://img138.imageshack.us/img138/5060/ss20120301145156.png)

**Comment by carimura** [comment]
Ah ya  ... this is because we have an MQ Heroku article and a Worker Heroku article both in category "platform".

Paddy ideas on how we should handle this one?

**Comment by paddycarver** [comment]
Yup, I'll fix this right now.
