### ISSUE TITLE
Need an Article on Merging Workers

### ISSUE THREAD

**Issue by paddycarver** [iron-io/docs#60]
Just had a customer in the public chat ask about merging workers, and they ended up turning to some of our old docs. Need to get the info from [this doc](https://sites.google.com/site/ironiodocs/worker/ruby/working-with-gems/merging-other-files) ported. I'd think it would be placed in the getting started on RoR article we have.

**Comment by frommww** [comment]
Thought there was an article there on merging workers. Need to be made multi-language as well as address Ruby and Ruby_ng gems. 

Definitely need to address the merging files/folders issue but then we also have ruby/ruby_ng disparities.

**Comment by carimura** [comment]
not pretty but here they are....
