### ISSUE TITLE
Missing correct Dockerfile in IronWorker Getting Started

### ISSUE THREAD

**Issue by bwalton** [iron-io/docs#605]
I'm working my way through the IronWorker getting started guide. The article here:
http://dev.iron.io/worker/getting_started/

Links to the correct Ruby Dockerfile, but doesn't display the correct code in the article itself:
`ENTRYPOINT ["ruby", "helloworld.rb"]`

Should be:
```
FROM iron/ruby

WORKDIR /app
ADD . /app

ENTRYPOINT ["ruby", "hello.rb"]
```

Small nitpick but it threw me off a bit when I was working my way through it.

Thanks!

**Comment by dylanz** [comment]
Brian!  I made a fix to this and will push soon.  Thanks for the heads up!! https://github.com/iron-io/docs/commit/d798849873824e06c24a6217a9bbc3336e3ed2e7
