### ISSUE TITLE
HTTP 401 Error: Invalid project/token combination

### ISSUE THREAD

**Issue by stofer-smith** [iron-io/docs#606]
I am getting this error, both when trying to use my queue and when trying to access it here...
https://hud-e.iron.io/mq/mq-aws-eu-west-1-1/projects/57e17e49ce60dc0007dd3506/queues#?q=
(HTTP 401 Error: Invalid project/token combination)

Thanks,
~s

**Comment by alex-litvak** [comment]
@stofer-smith Check please now
