### ISSUE TITLE
Replicate "Merging Gems, Models, Code" old docs section to dev.iron.io

### ISSUE THREAD

**Issue by thousandsofthem** [iron-io/docs#64]
Old docs location:
https://sites.google.com/site/ironiodocs/worker/ruby/working-with-gems

**Comment by treeder** [comment]
This entire section is missing: https://sites.google.com/site/ironiodocs/worker/ruby

**Comment by treeder** [comment]
This might be a good time to just move the Ruby stuff the gem github wiki. https://github.com/iron-io/iron_worker_ruby

**Comment by paddycarver** [comment]
Sounds like the consensus.

Maybe we should do an iron_worker_ruby article, too? Give it some presence here, so people can find it, with a brief introduction, then point to the iron_worker_ruby wiki?

**Comment by paddycarver** [comment]
This has been in the iron_worker_ruby wiki for some time. The Ruby language page now makes it decidedly documented.
