### ISSUE TITLE
Add a Limits section to both MQ and Worker

### ISSUE THREAD

**Issue by treeder** [iron-io/docs#65]
Limits for worker include:
- 60 minutes max run time
- 64k payload size
- etc.

Limits for MQ include:
- 64k message size

**Comment by paddycarver** [comment]
These are sprinkled throughout the API reference, but I kind of like having a section in that page for them.

Were you thinking a section in the API reference page, or a new page in reference? I'm not sure a new page makes sense, personally.

**Comment by treeder** [comment]
A separate page would  be nice, like:
http://docs.amazonwebservices.com/AmazonSimpleDB/latest/DeveloperGuide/SDBLimits.html

On Wed, Mar 21, 2012 at 11:41 AM, Paddy Foran <
reply@reply.github.com
