### ISSUE TITLE
not able to set the task progress in iron io.

### ISSUE THREAD

**Issue by DivyaPalanisamy001** [iron-io/docs#676]
I have made a rest call with iron.io url with project id and token to update the task progress. job is failed as some issue with the input data, And, I want to customize the reason of failure. But through rest call, progress is not updated in iron task info. Hence some invalid error message is shown to user when we do get task status..

**Comment by iron-frontend** [comment]
Can you please email support@iron.io with a link to your task and we can take a look at the issue.?  Thanks.
