### ISSUE TITLE
Document how to write your own clients from scratch

### ISSUE THREAD

**Issue by treeder** [iron-io/docs#69]
https://sites.google.com/site/ironiodocs/worker/api/running-code-on-ironworker

**Comment by paddycarver** [comment]
@treeder What does this entail, beyond the basic "Implement the API methods?"

**Comment by treeder** [comment]
This can probably be closed, implement api methods + packaging is what it would entail, but we link to packaging from the upload endpoint so should be good. You might want to review the packaging docs though.

**Comment by paddycarver** [comment]
Yup. That's #180.
