### ISSUE TITLE
Getting data in and out of a worker

### ISSUE THREAD

**Issue by treeder** [iron-io/docs#74]
Reference doc explaining:
- Data is brought into the worker/task from external data sources such as your database or s3, etc. 
- The payload should only include what is necessary to access those data sources and know what data to act upon. This includes database id's or query parameters, s3 urls, website urls, etc. 
- The results of the task should be stored back into the database or s3, etc.

**Comment by paddycarver** [comment]
Thinking about smushing this in with another doc, but yeah, agreed it needs to be there.

**Comment by paddycarver** [comment]
Would it be possible unassign me from this issue, or close the issue?
