### ISSUE TITLE
Add info about Heroku and PHPFog not allowing remote access to their databases

### ISSUE THREAD

**Issue by treeder** [iron-io/docs#79]
Put this on first page of Databases section. 

Include links to supporting documentation, eg for php fog: http://dev.appfog.com/features/article/database

Also include links to alternatives like Xeround and point out that they also have a free starter plan: http://xeround.com/mysql-cloud-db-overview/pricing/

**Comment by carimura** [comment]
We're working on access to their DB. Sounds like it's possible.

**Comment by paddycarver** [comment]
@carimura any update on that? Also, this sounds like something we'd put into the docs in THEIR dev center, not ours. Agreed?

**Comment by carimura** [comment]
@treeder we have access now to AppFog DB right?

@paddyforan well it should go in theirs, of course, but customers seem to bring this up often which means when using IronWorker it's a cause for confusion.

**Comment by treeder** [comment]
@carimura ya, I believe they opened it up to us a while ago.

**Comment by carimura** [comment]
this is no longer applicable
