### ISSUE TITLE
Add box on sidebar that says "this is open source... contribute..."

### ISSUE THREAD

**Issue by treeder** [iron-io/docs#82]
Like github help: http://help.github.com/

Put it in sidemenu_all.html so it's on every page.

**Comment by paddycarver** [comment]
Ken and I actually discussed this a bit when I was in town. What about a ribbon? "Fork me on Github"?

I'll put mocking them up on my to-do list. Aiming for Friday.

**Comment by treeder** [comment]
ribbon sounds cool, whatever works.

On Tue, Apr 17, 2012 at 11:11 PM, Paddy Foran <
reply@reply.github.com

**Comment by treeder** [comment]
@paddy any update on this?
