### ISSUE TITLE
Best Practices - IronMQ

### ISSUE THREAD

**Issue by frommww** [iron-io/docs#84]
Include best practices on getting data from IronMQ.

User:
Also, so are you saying it is not a best practice to read the queue size and loop over it? Rather it is better to simply read it and see if you get anything... I think I'm answering my own question...

Ken F.
Not wise to use queue size. just read and it'll return an empty queue message.
then you can sleep or adjust a scheduled task accordingly.
that's our fault for not including best practices on using queues.

**Comment by treeder** [comment]
+1, this would be very helpful stuff.

**Comment by paddycarver** [comment]
Would it be possible unassign me from this issue, or close the issue?
