### ISSUE TITLE
Article: How to use Scrapy with IronWorker

### ISSUE THREAD

**Issue by treeder** [iron-io/docs#93]

**Comment by turian** [comment]
I would love to see this.

**Comment by turian** [comment]
Or any Python distributed crawler.

**Comment by paddycarver** [comment]
I'll bump it up in priority. :) Watch this thread--when I clear off some of the more pressing stuff I'm doing, I'll work on this.

**Comment by paddycarver** [comment]
@turian Can I ask where you're running into difficulty? What would you like to see in an article? Trying to figure out how to approach this that won't end with us writing an example for every web scraper ever, because that's not really tenable.

**Comment by rajivseelam** [comment]
Installing scrapy and lxml should do for now. When I test my workers locally they work, when i upload it the build fails with errors:

```
 No package 'libffi' found

removing: _configtest.c _configtest.o

c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory

compilation terminated.
```
