### ISSUE TITLE
Put our months events in the community section

### ISSUE THREAD

**Issue by carimura** [iron-io/docs#95]
http://dev.iron.io/community/

Check the last newsletter I sent for events... Also @frommww do you have dates for the meetups?

Include our May 31st: Drinkup

**Comment by paddycarver** [comment]
Created a Google Calendar for this and gave admin rights to you, Ken, and Travis. Let me know what to put in there, and I'll add it, if you guys don't want to be bothered. :)

I'll come up with some slick way to auto-update dev using the calendar.

**Comment by carimura** [comment]
Interesting... we _have_ a google cal already for marketing and events, but it may have things that won't belong on that page. Shuold we keep the separate one?
